#!/bin/bash

# Script Name: Ops Challenge 02
# Author: David Armstrong
# Date of last revision: 09-01-2020
# Description of purpose: to write syslog data to a file and include the date and time

# Declaration of variables

full_date=`date +%D`
full_time=`date +%T`

# Declaration of functions

function date_syslog(){
cp -r /var/log/syslog ~/bin
echo "Today's Date and Time:" >> syslog
echo $full_date $full_time >> syslog
}


# Main

date_syslog

# End
