#!/bin/bash

# Script Name: Ops Challenge 05
# Author: David Armstrong
# Date of last revision: 09-04-2020
# Description of purpose: to clear the content of files

# Declaration of variables
sys_path="/var/log/syslog"
wtmp_path="/var/log/wtmp"

# Declare functions
function clear_file(){
echo "Here is the original text:"
cat $1
# truncate file to 0 characters
sudo truncate $1 --size 0
echo "Here is the cleared text:"
cat $1
}

# Main
clear_file $sys_path
clear_file $wtmp_path

# End
